// <auto-generated />
using Igor.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Igor.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20241016123513_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Igor.Models.Folha", b =>
                {
                    b.Property<int>("folhaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ano")
                        .HasColumnType("INTEGER");

                    b.Property<double>("impostoFgts")
                        .HasColumnType("REAL");

                    b.Property<double>("impostoInss")
                        .HasColumnType("REAL");

                    b.Property<double>("impostoIrrf")
                        .HasColumnType("REAL");

                    b.Property<int>("mes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<double>("salarioBruto")
                        .HasColumnType("REAL");

                    b.Property<double>("salarioLiquido")
                        .HasColumnType("REAL");

                    b.Property<double>("valor")
                        .HasColumnType("REAL");

                    b.HasKey("folhaId");

                    b.ToTable("Folhas");
                });

            modelBuilder.Entity("Igor.Models.Funcionario", b =>
                {
                    b.Property<int>("funcionarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpf")
                        .HasColumnType("TEXT");

                    b.Property<int>("folhaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.HasKey("funcionarioId");

                    b.HasIndex("folhaId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("Igor.Models.Funcionario", b =>
                {
                    b.HasOne("Igor.Models.Folha", "Folha")
                        .WithMany()
                        .HasForeignKey("folhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folha");
                });
#pragma warning restore 612, 618
        }
    }
}
